services:
  - type: web
    name: sigot-api
    runtime: node
    buildCommand: npm install --ignore-scripts && npx prisma generate && npx prisma migrate deploy && node prisma/seed.js
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 8h
      - key: DATABASE_URL
        value: postgresql://sigot_db_j19h_user:qUeVcsf2j4ioexJ9L2jAZ39WJmelsWM9@dpg-d7joncvavr4c73cgqo50-a/sigot_db_j19h
