services:
  - type: web
    name: sigot-api
    runtime: node
    buildCommand: npm install --ignore-scripts && npx prisma generate && npx prisma migrate deploy
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 8h
      - key: DATABASE_URL
        sync: false
